<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_infokatalon.com_to-top</name>
   <tag></tag>
   <elementGuidId>adc295a2-b003-4fd2-8977-7eef2d1a2d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#to-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='to-top']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>104d4c8e-f893-4922-9c50-a6dd07272167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>to-top</value>
      <webElementGuid>36e1a1d6-5664-41d8-bcb1-6c0850538412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#top</value>
      <webElementGuid>4f8d0b1e-3a7b-4b8e-8767-da185be49092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dark btn-lg</value>
      <webElementGuid>9180e522-3a32-4f69-89b0-fc049db57e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to-top&quot;)</value>
      <webElementGuid>a19e637f-4fb0-496d-bfad-18029dac8ee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='to-top']</value>
      <webElementGuid>ee54af3b-9c7e-4743-8ac9-fb983d361edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@katalon.com'])[1]/following::a[4]</value>
      <webElementGuid>3972171d-64a0-4bb7-92c8-d66bfb50991a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(678) 813-1KMS'])[1]/following::a[5]</value>
      <webElementGuid>87723698-24c4-4675-bdd3-7116d3b40463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'to-top', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>0186708a-8b26-423b-8ff1-90d4e771d928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#top')]</value>
      <webElementGuid>122d5e6b-38a4-4da3-a576-0bbe748fa91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/a</value>
      <webElementGuid>15a7145c-14d4-49e6-93fd-a845bfc174d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'to-top' and @href = '#top']</value>
      <webElementGuid>89611dce-15b3-4603-bbdc-8d8a598b70a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
